spring:
  datasource:
    url : jdbc:mysql://localhost:3306/OAuthTest
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create # (1) 스키마 자동 생성 //create-drop,update
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

  devtools:
    livereload:
      enabled: true

  logging:
    level:
      org:
        springframework:
          orm:
            jpa: DEBUG

  server:
    servlet:
      encoding:
        force-response: true